from django.conf.urls import url

from . import views

app_name = 'main'
urlpatterns = [
    url(r'^app/check/$',views.app_check),
    url(r'^message/new/$',views.message_new),
    url(r'^message/remind/all/$',views.message_remind_all),
    url(r'^message/all/$',views.message_all),
    url(r'^message/detail/$',views.message_detail),
    url(r'^message/comment/$',views.message_comment),
    url(r'^account/login/$',views.login),
    url(r'^account/signup/$',views.signup),
    url(r'^account/short_message_code/$',views.short_message_code),
    url(r'^account/logout/$',views.logout),
    url(r'^account/info/$',views.account_info),
    url(r'^account/change_name/$',views.change_name),
    url(r'^account/change_password/$',views.change_password),
    url(r'^account/is_logged_in/$',views.is_logged_in),
    url(r'^account/daily_sign/$',views.daily_sign),
    url(r'^account/buy/$',views.buy),
    url(r'^account/buy_done/$',views.buy_done),
    url(r'^account/buy_done_check/$',views.buy_done_check),
    url(r'^account/redeem/(?P<code>.+)/$',views.redeem),
    url(r'^feedback/$',views.set_feedback),
    url(r'^items/(?P<category>.+)/$',views.items_filter),
    url(r'^groups/all/$',views.groups_all),
    url(r'^groups/new/$',views.groups_new),
    url(r'^groups/change_name/$', views.groups_name_edit),
    url(r'^groups/update_contacts/$', views.update_contacts),
    url(r'^groups/delete/$',views.groups_delete),
    url(r'^information/(?P<key>.+)/(?P<type>.+)/',views.get_information),
    # url(r'^$',views.index,name='index'),
    # url(r'^index/$',views.index,name='index'),
    # url(r'^story/add/$',views.story_add,name='story_add'),
    # url(r'^story/(?P<story_id>[0-9]+)/$',views.story_detail,name='story_detail'),
    # url(r'^story/(?P<story_id>[0-9]+)/reply/$',views.story_reply,name='story_reply'),
    # url(r'^like/$',views.like,name='like'),
    # url(r'^about/$', views.about, name='about'),
    # url(r'^me/$', views.me_setting, name='me'), #默认进入的是“个人设置”
    # url(r'^me/created/$', views.me_created, name='me_created'),
    # url(r'^me/participated/$', views.me_participated, name='me_participated'),
    # url(r'^me/setting/$', views.me_setting, name='me_setting'),
    # url(r'^me/modify/$', views.me_modify, name='me_modify'),
    # url(r'^me/changepwd/$', views.me_changepwd, name='me_changepwd'),
    # url(r'^me/avatar/$', views.me_avatar, name='me_avatar'),
]