# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='type',
            field=models.CharField(default='普通用户', max_length=20),
        ),
    ]
