# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='link',
            name='short_link',
            field=models.CharField(default='', max_length=30),
        ),
    ]
