# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161022_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.CharField(default='[]', max_length=12000),
        ),
    ]
