# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161022_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='received_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='total_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
