# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161022_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='text_surplus',
            new_name='text_limit',
        ),
    ]
