# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161022_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='text_limit',
            new_name='text_surplus',
        ),
    ]
