# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment_able',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagedatanotice',
            name='comments',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
