# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_messagedatanotice_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='upgrade', max_length=20),
            preserve_default=False,
        ),
    ]
