# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_redeemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50000),
        ),
    ]
