# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_auto_20161030_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcode',
            name='who_used',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
