# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_userinfo_last_daily_sign_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='last_daily_sign_time',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_daily_sign_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
