# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_daily_sign_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(max_length=15),
        ),
    ]
