# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_redeemcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='invite_code',
            field=models.CharField(default='233145', max_length=10),
            preserve_default=False,
        ),
    ]
