# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='FeedBack',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
