# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bells_read',
            field=models.ManyToManyField(related_name='read_user', to='main.Bell'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bells_unread_major',
            field=models.ManyToManyField(related_name='unread_major_user', to='main.Bell'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bells_unread_minor',
            field=models.ManyToManyField(related_name='unread_minor_user', to='main.Bell'),
        ),
    ]
