# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20161125_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bell',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
