# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20161125_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bell',
            name='sender',
            field=models.CharField(default='sparker', max_length=10),
            preserve_default=False,
        ),
    ]
