# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_userinfo_invite_code'),
        ('main', '0035_bell_sender'),
    ]

    operations = [
    ]
